version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-devtools
    versions:
    - 4.10.1
    - 4.11.0
    - 4.12.0
    - 4.12.1
  - dependency-name: three
    versions:
    - 0.125.1
    - 0.125.2
    - 0.126.0
  - dependency-name: react-native
    versions:
    - 0.63.4
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
